/**
 * ====================================================================================
 * PREMIUM RICE & GRAIN STORE - UNIFIED BACKEND ENTERPRISE ARCHITECTURE
 * ====================================================================================
 * System: Mwea Rice Hub Enterprise API Engine
 * Version: 3.5.0-ENTERPRISE-RENDER
 * Platform: Node.js / Express / Socket.IO / Sequelize ORM / PayHero API / Nodemailer
 * Deployment: Render Cloud Infrastructure (Production Optimized)
 * 
 * Description:
 * Complete, single-file server engine handling real-time WebSocket state synchronization,
 * dynamic location logistics hierarchies (loaded directly from kenya_locations.json),
 * full-stack shopping cart management, M-Pesa STK push & webhooks via PayHero,
 * administrative analytics, account creation OTP verification, password reset OTP,
 * email verification via Nodemailer SMTP, and dynamic hero carousel settings.
 * ====================================================================================
 */

import dns from 'dns';
// Enforce IPv4 lookup resolution order for consistent DNS resolution on cloud environments like Render
dns.setDefaultResultOrder('ipv4first');

import express from 'express';
import { createServer } from 'http';
import { Server as SocketIOServer } from 'socket.io';
import { Sequelize, DataTypes, Op } from 'sequelize';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import cors from 'cors';
import dotenv from 'dotenv';
import multer from 'multer';
import fs from 'fs';
import path, { dirname } from 'path';
import { fileURLToPath } from 'url';
import axios from 'axios';
import nodemailer from 'nodemailer';

// Payment & Webhook Controller Integrations
import { handlePayHeroWebhook } from './controllers/webhookController.js';
import { initiatePayHeroPayment } from './controllers/paymentController.js';

// Initialize environment variables from .env file
dotenv.config();

// Initialize the Express app instance
const app = express();

app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', 'https://premium-rice-store-3.onrender.com');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.header('Access-Control-Allow-Credentials', 'true');
  
  if (req.method === 'OPTIONS') {
    return res.sendStatus(200);
  }
  next();
});
/**
 * ==========================================
 * 0. SYSTEM INITIALIZATION, PATHS & CONSTANTS
 * ==========================================
 */
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const NODE_ENV = process.env.NODE_ENV || 'development';
const isProduction = NODE_ENV === 'production';
const hostname = process.env.HOSTNAME || '0.0.0.0';
const port = parseInt(process.env.PORT || '5000', 10);
const JWT_SECRET = process.env.JWT_SECRET || 'SUPER_SECRET_RICE_GRAIN_STORE_KEY_2026';
const RENDER_BASE_URL = process.env.BASE_URL || 'https://premium-rice-store-7.onrender.com';

console.log('====================================================================');
console.log('🚀 Booting Mwea Rice Hub Enterprise Architecture...');
console.log(`🌍 Environment: ${NODE_ENV.toUpperCase()}`);
console.log(`⚡ Execution Directory: ${__dirname}`);
console.log(`📡 Base Deployment Target URL: ${RENDER_BASE_URL}`);
console.log('====================================================================');

/**
 * ==========================================
 * DYNAMIC KENYA LOCATIONS LOADER UTILITY
 * ==========================================
 * Safely reads and parses 'kenya_locations.json' generated by convert.js.
 * Eliminates hardcoded location literals while providing safe fallbacks.
 */
function loadKenyaLocationsDataset() {
  const primaryLocationsPath = path.join(__dirname, 'kenya_locations.json');
  const secondaryLocationsPath = path.join(__dirname, 'public', 'kenya_locations.json');
  
  let selectedPath = null;
  if (fs.existsSync(primaryLocationsPath)) {
    selectedPath = primaryLocationsPath;
  } else if (fs.existsSync(secondaryLocationsPath)) {
    selectedPath = secondaryLocationsPath;
  }

  let rawJsonData = null;
  let countyOverrides = {};
  let logisticsHierarchy = {};

  if (selectedPath) {
    try {
      console.log(`📂 Reading Kenya locations dataset directly from: ${selectedPath}`);
      const fileBuffer = fs.readFileSync(selectedPath, 'utf8');
      rawJsonData = JSON.parse(fileBuffer);

      // Structure check: Handles both formatted { counties, hierarchy } and nested county trees
      if (rawJsonData && typeof rawJsonData === 'object') {
        if (rawJsonData.counties && rawJsonData.hierarchy) {
          countyOverrides = rawJsonData.counties;
          logisticsHierarchy = rawJsonData.hierarchy;
        } else if (rawJsonData.counties && !rawJsonData.hierarchy) {
          countyOverrides = rawJsonData.counties;
          logisticsHierarchy = rawJsonData;
        } else {
          // Build hierarchy and county fee map dynamically from top-level keys
          logisticsHierarchy = rawJsonData;
          Object.keys(rawJsonData).forEach((countyName) => {
            // Assign default regional transport charges based on common geographical zones
            const lowerName = countyName.toLowerCase();
            if (lowerName.includes('nairobi') || lowerName.includes('kirinyaga') || lowerName.includes('kiambu')) {
              countyOverrides[countyName] = 200;
            } else if (lowerName.includes('mombasa') || lowerName.includes('kwale') || lowerName.includes('kilifi')) {
              countyOverrides[countyName] = 500;
            } else if (lowerName.includes('mandera') || lowerName.includes('wajir') || lowerName.includes('turkana')) {
              countyOverrides[countyName] = 800;
            } else {
              countyOverrides[countyName] = 350;
            }
          });
        }
        console.log(`✅ Successfully loaded location dataset. Total Counties Identified: ${Object.keys(countyOverrides).length}`);
      }
    } catch (readErr) {
      console.error(`❌ Failed to parse kenya_locations.json dataset: ${readErr.message}`);
    }
  } else {
    console.warn('⚠️ WARNING: kenya_locations.json was not found on disk. Initializing basic empty location structures.');
  }

  return { countyOverrides, logisticsHierarchy, rawJsonData };
}

/**
 * ==========================================
 * EMAIL CONFIGURATION (Nodemailer SMTP Transporter)
 * ==========================================
 */
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT || '587', 10),
  secure: process.env.SMTP_PORT === '465', // true for 465, false for 587 / submit
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
  tls: {
    rejectUnauthorized: false // Tolerant TLS handshake for cloud hosting environments
  }
});

const EMAIL_FROM = process.env.EMAIL_FROM || process.env.EMAIL_USER || 'noreply@mwearicehub.com';
const SENDER_NAME = 'Mwea Rice Hub Enterprise';

/**
 * Helper function to send email OTP via Nodemailer for Account Creation & Password Reset
 * @param {string} toEmail 
 * @param {string} toName 
 * @param {string} otpCode 
 * @param {string} type - 'reset' | 'signup' | 'account_creation'
 */
const sendOtpEmail = async (toEmail, toName, otpCode, type = 'reset') => {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    console.warn('⚠️ WARNING: SMTP Email credentials (EMAIL_USER / EMAIL_PASS) are missing in environment variables.');
  }

  const isSignup = type === 'signup' || type === 'account_creation';
  const subject = isSignup 
    ? '🔐 Account Verification OTP Code - Mwea Rice Hub' 
    : '🔐 Your Password Reset OTP Code - Mwea Rice Hub';
  const title = isSignup ? 'Account Verification' : 'Password Reset Request';
  const description = isSignup
    ? 'Thank you for signing up with Mwea Rice Hub. Please use the following 6-digit One-Time Password (OTP) to verify and activate your new account:'
    : 'You recently requested to reset your password for your Mwea Rice Hub account. Please use the following 6-digit One-Time Password (OTP) to verify your request:';

  const mailOptions = {
    from: `"${SENDER_NAME}" <${EMAIL_FROM}>`,
    to: toEmail,
    subject: subject,
    html: `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 28px; color: #2c3e50; max-width: 620px; margin: auto; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.05);">
        <div style="text-align: center; margin-bottom: 24px;">
          <h1 style="color: #2e7d32; margin: 0; font-size: 26px; font-weight: 700;">🌾 Mwea Rice Hub</h1>
          <p style="color: #64748b; font-size: 14px; margin-top: 4px;">Direct From Mwea Paddy Fields to Your Doorstep</p>
        </div>
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
        <h2 style="color: #1e293b; font-size: 20px; margin-top: 0;">${title}</h2>
        <p style="font-size: 15px; line-height: 1.6;">Hello <strong>${toName || 'Valued Customer'}</strong>,</p>
        <p style="font-size: 15px; line-height: 1.6;">${description}</p>
        <div style="background: #f0fdf4; border: 2px dashed #22c55e; color: #15803d; font-size: 36px; font-weight: 800; text-align: center; padding: 20px; border-radius: 10px; letter-spacing: 8px; margin: 24px 0;">
          ${otpCode}
        </div>
        <p style="font-size: 13px; color: #64748b; line-height: 1.5;">This verification code is strictly valid for <strong>10 minutes</strong>. If you did not initiate this request, please secure your account or disregard this email.</p>
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;" />
        <p style="font-size: 12px; color: #94a3b8; text-align: center; margin: 0;">&copy; ${new Date().getFullYear()} Mwea Rice Hub Kenya. All Rights Reserved.</p>
      </div>
    `
  };

  return await transporter.sendMail(mailOptions);
};

/**
 * Helper function to send SMS OTP based on standard gateway logic.
 * Update the axios block with your specific SMS provider API documentation once available.
 * @param {string} phoneNumber 
 * @param {string} otpCode 
 * @param {string} type - 'reset' | 'signup'
 */
const sendOtpSms = async (phoneNumber, otpCode, type = 'reset') => {
  try {
    if (!phoneNumber) return;
    
    // Normalize phone numbers to standard Kenyan +254 format
    const formattedPhone = phoneNumber.startsWith('0') 
      ? `+254${phoneNumber.substring(1)}` 
      : phoneNumber;
      
    const message = type === 'signup' 
      ? `Your Mwea Rice Hub account verification OTP is ${otpCode}. Valid for 10 mins.`
      : `Your Mwea Rice Hub password reset OTP is ${otpCode}. Valid for 10 mins.`;

    console.log(`📱 [SMS DISPATCH] Triggering SMS to ${formattedPhone}: ${message}`);
    
    // --- SMS API PLACEHOLDER ---
    // Uncomment and replace with the exact endpoint and payload from your SMS PDF
    /*
    await axios.post('YOUR_SMS_GATEWAY_URL_HERE', {
      api_key: process.env.SMS_API_KEY,
      to: formattedPhone,
      message: message
    });
    */
    
    return true;
  } catch (error) {
    console.error(`❌ Failed to send SMS OTP to ${phoneNumber}:`, error.message);
  }
};

/**
 * Helper function to retrieve and construct PayHero Basic Auth Headers cleanly
 */
const getPayHeroAuthHeader = () => {
  if (process.env.PAYHERO_BASIC_AUTH) {
    const cleanAuth = process.env.PAYHERO_BASIC_AUTH.replace(/[\r\n]+/g, '').trim();
    return cleanAuth.startsWith('Basic ') ? cleanAuth : `Basic ${cleanAuth.replace(/^Basic/i, '').trim()}`;
  }
  if (process.env.PAYHERO_API_KEY && process.env.PAYHERO_API_SECRET) {
    const creds = `${process.env.PAYHERO_API_KEY.trim()}:${process.env.PAYHERO_API_SECRET.trim()}`;
    return `Basic ${Buffer.from(creds).toString('base64')}`;
  }
  const fallbackRaw = 'Basic cnBqZHU3YWJyWG03SWdqcDBI\\nBF:NHFvR\\nV32XR99cDq\\nGf3igKB3R0A5vRtgTMJ7Jpfm'
    .replace(/\\[rn]/g, '')
    .replace(/[\r\n]+/g, '')
    .trim();
  return fallbackRaw.startsWith('Basic ') ? fallbackRaw : `Basic ${fallbackRaw.replace(/^Basic/i, '').trim()}`;
};

const PAYHERO_CHANNEL_ID = Number(process.env.PAYHERO_CHANNEL_ID || 11668);

/**
 * ==========================================
 * 1. UPLOAD DIRECTORY & ASSET CONFIGURATION
 * ==========================================
 */
const uploadDir = path.join(__dirname, 'public', 'uploads');
const imagesDir = path.join(__dirname, 'public', 'images');

try {
  if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
    console.log('📁 Created missing upload directory at:', uploadDir);
  }

  if (!fs.existsSync(imagesDir)) {
    fs.mkdirSync(imagesDir, { recursive: true });
    console.log('📁 Created missing images directory at:', imagesDir);
  }
} catch (fsErr) {
  console.error('❌ Failed to verify or build static public storage directories:', fsErr.message);
}

// Multer Storage Configuration for File Uploads
const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, uploadDir),
  filename: (req, file, cb) => {
    const cleanFileName = file.originalname.replace(/[^a-zA-Z0-9.-]/g, '_');
    cb(null, `${Date.now()}-${cleanFileName}`);
  }
});

const upload = multer({ 
  storage,
  limits: { fileSize: 15 * 1024 * 1024 }, // 15MB file upload limit
  fileFilter: (req, file, cb) => {
    if (file.mimetype.startsWith('image/')) {
      cb(null, true);
    } else {
      cb(new Error('Only valid image files are permitted for upload.'), false);
    }
  }
});

/**
 * ==========================================
 * 2. DATABASE SCHEMAS, MODELS & ASSOCIATIONS
 * ==========================================
 */
import { 
  User, 
  RiceProduct, 
  Order, 
  Review, 
  AdminLog, 
  SystemConfig, 
  sequelize 
} from './lib/db.js';

// User Persistent Shopping Cart Database Model Definition
const Cart = sequelize.models.Cart || sequelize.define('Cart', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  userId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: User,
      key: 'id'
    }
  },
  productId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: RiceProduct,
      key: 'id'
    }
  },
  quantity: {
    type: DataTypes.INTEGER,
    defaultValue: 1,
    allowNull: false,
    validate: {
      min: 1
    }
  }
}, {
  timestamps: true,
  tableName: 'Carts'
});

// Define Relational Model Associations
if (Cart && RiceProduct && !Cart.associations.RiceProduct) {
  Cart.belongsTo(RiceProduct, { foreignKey: 'productId', as: 'product', onDelete: 'CASCADE' });
}
if (Cart && User && !Cart.associations.User) {
  Cart.belongsTo(User, { foreignKey: 'userId', as: 'user', onDelete: 'CASCADE' });
}

/**
 * ==========================================
 * 3. LIVE FLASH HARVEST SALE ENGINE UTILS
 * ==========================================
 */
let flashSaleState = {
  active: false,
  endTime: null,
  countdownIntervalId: null
};

function initializeFlashSaleEngine(io) {
  SystemConfig.findOne({ where: { key: 'black_friday' } }).then((config) => {
    if (config && config.value && config.value.active) {
      const remainingTime = new Date(config.value.endTime).getTime() - Date.now();
      if (remainingTime > 0) {
        flashSaleState.active = true;
        flashSaleState.endTime = config.value.endTime;
        startFlashSaleCountdown(io);
        console.log(`🔥 Flash Harvest Sale Engine Restored! Active until: ${flashSaleState.endTime}`);
      } else {
        config.value = { ...config.value, active: false };
        config.changed('value', true);
        config.save();
        console.log('🏁 Expired Flash Harvest Sale state automatically deactivated in DB.');
      }
    }
  }).catch(err => console.error('❌ Failed to boot Flash Sale Engine state:', err.message));
}

function startFlashSaleCountdown(io) {
  if (flashSaleState.countdownIntervalId) {
    clearInterval(flashSaleState.countdownIntervalId);
  }
  
  flashSaleState.countdownIntervalId = setInterval(() => {
    const totalRemaining = new Date(flashSaleState.endTime).getTime() - Date.now();
    if (totalRemaining <= 0) {
      clearInterval(flashSaleState.countdownIntervalId);
      flashSaleState.active = false;
      flashSaleState.endTime = null;
      io.emit('blackFridayEnded', { active: false });
      
      SystemConfig.findOne({ where: { key: 'black_friday' } }).then(config => {
        if (config) {
          config.value = { ...config.value, active: false };
          config.changed('value', true);
          config.save();
        }
      });
      console.log('🏁 Flash Harvest Sale window has officially closed.');
    } else {
      io.emit('blackFridayTick', {
        active: true,
        endTime: flashSaleState.endTime,
        msRemaining: totalRemaining
      });
    }
  }, 1000);
}

/**
 * ==========================================
 * 4. AUTHENTICATION & SECURITY MIDDLEWARES
 * ==========================================
 */
const authenticateToken = (req, res, next) => {
  const authHeader = req.headers['authorization'] || req.headers['Authorization'];
  let token = authHeader && authHeader.startsWith('Bearer ') ? authHeader.split(' ')[1] : authHeader;
  
  if (!token && req.query && req.query.token) {
    token = req.query.token;
  }
  
  if (token) {
    token = token.trim().replace(/^["']|["']$/g, '');
  }

  if (!token || token === 'null' || token === 'undefined' || token === '') {
    return res.status(401).json({ error: 'Authentication token is required to access this resource.' });
  }

  jwt.verify(token, JWT_SECRET, (err, decodedUser) => {
    if (err) {
      console.log(`DEBUG: Auth Token Verification Failed - ${err.message}`);
      return res.status(403).json({ error: 'Token is invalid or expired. Please sign in again.' });
    }
    req.user = decodedUser;
    next();
  });
};

const requireAdmin = async (req, res, next) => {
  try {
    if (!req.user || !req.user.id) {
      return res.status(401).json({ error: 'User identification details missing from session token.' });
    }
    const userInstance = await User.findByPk(req.user.id);
    if (!userInstance || userInstance.role !== 'admin') {
      console.log(`DEBUG: Unauthorized Administrative Access Attempted by User ID: ${req.user.id}`);
      return res.status(403).json({ error: 'Access Denied. Elevated Administrator privileges are required.' });
    }
    if (!userInstance.isActive) {
      return res.status(403).json({ error: 'Access Denied. Your administrator account is suspended or disabled.' });
    }
    req.adminUser = userInstance;
    next();
  } catch (error) {
    console.error('DEBUG: Administrative Role Evaluation Error:', error);
    res.status(500).json({ error: 'Internal administrative role security evaluation failure.' });
  }
};

/**
 * ==========================================
 * 5. CORE SERVER & DATABASE BOOTSTRAP ENGINE
 * ==========================================
 */
async function startServer() {
  try {
    // Authenticate database connectivity
    await sequelize.authenticate();
    
    // Auto migration checks for dynamic reward points, buying prices & account verification columns
    try {
      const queryInterface = sequelize.getQueryInterface();
      const userTable = await queryInterface.describeTable('Users');
      if (!userTable.rewardPoints) {
        await queryInterface.addColumn('Users', 'rewardPoints', {
          type: DataTypes.FLOAT,
          defaultValue: 0,
          allowNull: false
        });
        console.log('✅ Synchronized database column: Users.rewardPoints');
      }

      if (!userTable.isVerified) {
        await queryInterface.addColumn('Users', 'isVerified', {
          type: DataTypes.BOOLEAN,
          defaultValue: true,
          allowNull: false
        });
        console.log('✅ Synchronized database column: Users.isVerified');
      }

      if (!userTable.verificationOtp) {
        await queryInterface.addColumn('Users', 'verificationOtp', {
          type: DataTypes.STRING,
          allowNull: true
        });
        console.log('✅ Synchronized database column: Users.verificationOtp');
      }

      if (!userTable.verificationOtpExpires) {
        await queryInterface.addColumn('Users', 'verificationOtpExpires', {
          type: DataTypes.DATE,
          allowNull: true
        });
        console.log('✅ Synchronized database column: Users.verificationOtpExpires');
      }
      
      const productTable = await queryInterface.describeTable('RiceProducts');
      if (!productTable.buyingPrice) {
        await queryInterface.addColumn('RiceProducts', 'buyingPrice', {
          type: DataTypes.FLOAT,
          defaultValue: 0,
          allowNull: true
        });
        console.log('✅ Synchronized database column: RiceProducts.buyingPrice');
      }
    } catch (colErr) {
      console.log('DEBUG: Database table structure sync verified.');
    }

    await sequelize.sync();
    
    const currentMode = process.env.DB_MODE === 'cloud' ? '☁️ AIVEN / CLOUD POSTGRES' : '🏠 RENDER / LOCAL DB';
    console.log(`🍃 Database Connected Successfully! Running Mode: [ ${currentMode} ]`);

    const expressApp = express();
    expressApp.set('trust proxy', true);

    const server = createServer(expressApp);

    // Dynamic CORS configuration accepting Render domains, local clients, and mobile wrappers
    const corsOptions = {
      origin: (origin, callback) => {
        if (!origin || origin.includes('localhost') || origin.includes('127.0.0.1') || origin.endsWith('.onrender.com')) {
          callback(null, true);
        } else {
          callback(null, true);
        }
      },
      methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH'],
      allowedHeaders: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept'],
      credentials: true
    };
    
    expressApp.use(cors(corsOptions));
    expressApp.use(express.json({ limit: '50mb' }));
    expressApp.use(express.urlencoded({ limit: '50mb', extended: true }));

    // Serve static files from public, uploads, and images directories
    expressApp.use(express.static(path.join(__dirname, 'public')));
    expressApp.use('/uploads', express.static(path.join(__dirname, 'public', 'uploads')));
    expressApp.use('/images', express.static(path.join(__dirname, 'public', 'images')));

    // Initialize Default System Configuration Entries
    await SystemConfig.findOrCreate({ where: { key: 'transport_fee' }, defaults: { value: 250 } });
    await SystemConfig.findOrCreate({ where: { key: 'black_friday' }, defaults: { value: { active: false, endTime: null } } });
    
    await SystemConfig.findOrCreate({
      where: { key: 'mpesa_config' },
      defaults: {
        value: {
          paybillNumber: '522522',
          paybillAccount: 'MWEARICE',
          tillNumber: '889900',
          stkEnabled: true
        }
      }
    });

    // =========================================================================
    // LOAD REAL KENYA LOCATIONS DATASET DYNAMICALLY FROM JSON FILE
    // =========================================================================
    const { countyOverrides, logisticsHierarchy, rawJsonData } = loadKenyaLocationsDataset();

    await SystemConfig.findOrCreate({ 
      where: { key: 'county_overrides' }, 
      defaults: { value: countyOverrides } 
    });

    await SystemConfig.findOrCreate({ 
      where: { key: 'logistics_hierarchy' }, 
      defaults: { value: logisticsHierarchy } 
    });

    // Save full JSON dataset in SystemConfig if available for deep front-end search
    if (rawJsonData) {
      await SystemConfig.findOrCreate({
        where: { key: 'kenya_locations_full' },
        defaults: { value: rawJsonData }
      });
    }

    // --- EXPANDED 10-FIELD HERO CONFIGURATION DEFAULT ---
    await SystemConfig.findOrCreate({
      where: { key: 'hero_settings' },
      defaults: {
        value: {
          type: 'video',
          url: 'https://www.youtube.com/embed/gjZAThNHGwI?start=6&autoplay=1&mute=1&loop=1&playlist=gjZAThNHGwI',
          title: 'Direct From Mwea Paddy Fields',
          subtitle: '100% Pure Aromatic Pishori Rice harvested and delivered straight to your doorstep.',
          badgeText: '🌾 100% Authentic Mwea Harvest',
          buttonText: 'Shop Fresh Harvest Now',
          buttonLink: '/catalog',
          secondaryButtonText: 'View Flash Deals',
          secondaryButtonLink: '#flash-sales',
          overlayOpacity: 0.4,
          alignment: 'center',
          autoPlay: true,
          videoDuration: 5,
          imageDuration: 4
        }
      }
    });

    await SystemConfig.findOrCreate({
      where: { key: 'homepage_carousel' },
      defaults: {
        value: [
          { 
            id: "1", 
            type: 'video', 
            url: 'https://www.youtube.com/embed/gjZAThNHGwI?start=6&autoplay=1&mute=1&loop=1&playlist=gjZAThNHGwI', 
            title: 'Mwea Paddy Harvest Live', 
            subtitle: 'Direct from rich Kenyan soil into your kitchen.',
            duration: 5
          },
          { 
            id: "2", 
            type: 'image', 
            url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80', 
            title: 'Pure Mwea Pishori Grade 1', 
            subtitle: 'Unmatched aroma and long-grain perfection.',
            duration: 4
          },
          { 
            id: "3", 
            type: 'image', 
            url: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=1200&q=80', 
            title: 'Wholesale & Bulk Sack Delivery', 
            subtitle: 'Available in 5kg, 10kg, 25kg, and 50kg sacks with discounted transport.',
            duration: 3
          },
          { 
            id: "4", 
            type: 'image', 
            url: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=1200&q=80', 
            title: 'Premium Imported Basmati', 
            subtitle: 'Aged to perfection for fluffy, non-sticky ceremonial cooking.',
            duration: 4
          }
        ]
      }
    });

    // Seed Default Rice Products Catalog if empty
    const existingFeaturedCount = await RiceProduct.count();
    if (existingFeaturedCount === 0) {
      await RiceProduct.bulkCreate([
        {
          brandName: 'Pure Mwea Pishori Grade 1',
          variety: 'Aromatic Pishori',
          weightKg: 5,
          basePrice: 1250,
          buyingPrice: 950,
          flashSalePrice: 1100,
          stockQuantity: 150,
          imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
          isAvailable: true
        },
        {
          brandName: 'Super Aromatic Basmati',
          variety: 'Long Grain Basmati',
          weightKg: 10,
          basePrice: 2400,
          buyingPrice: 1800,
          flashSalePrice: 2150,
          stockQuantity: 80,
          imageUrl: 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=800&q=80',
          isAvailable: true
        },
        {
          brandName: 'Biryani Special Feast Grain',
          variety: 'Kaisari Long Grain',
          weightKg: 25,
          basePrice: 5200,
          buyingPrice: 4000,
          flashSalePrice: 4800,
          stockQuantity: 40,
          imageUrl: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80',
          isAvailable: true
        },
        {
          brandName: 'Whole Grain Brown Pishori',
          variety: 'Brown Nutritious Rice',
          weightKg: 5,
          basePrice: 1400,
          buyingPrice: 1050,
          flashSalePrice: 1250,
          stockQuantity: 60,
          imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
          isAvailable: true
        }
      ]);
      console.log('🌾 Seeded default 4 Featured Grain selection products into database catalog.');
    }

    // Google Sign-In Account Synchronization Endpoint
    expressApp.post('/api/sync/google', async (req, res) => {
      const { googleId, fullName, email } = req.body || {};
      
      if (!googleId) {
        console.error("DEBUG: google-sync received an empty payload");
        return res.status(400).json({ error: "Missing identity credentials" });
      }

      try {
        let user = await User.findOne({ where: { googleId } });
        if (!user) {
          user = await User.create({ 
            googleId, 
            fullName: fullName || 'Google User', 
            email, 
            role: 'user',
            isVerified: true,
            isActive: true
          });
          console.log(`✨ Created fresh database profile for Google user: ${fullName}`);
        } else {
          console.log(`🔐 Verified existing database profile for Google user: ${fullName}`);
        }
        res.status(200).json({ message: "User profile synchronized", user });
      } catch (error) {
        console.error("Database Sync Error:", error);
        res.status(500).json({ error: "Database Synchronization Failed" });
      }
    });

    // Real-Time Socket.IO Server Setup
    const io = new SocketIOServer(server, { 
      cors: corsOptions
    });

    initializeFlashSaleEngine(io);

    io.on('connection', (socket) => {
      if (flashSaleState.active) {
        socket.emit('blackFridayTick', { active: true, endTime: flashSaleState.endTime });
      }
      
      socket.on('joinAdminChannel', (token) => {
        jwt.verify(token, JWT_SECRET, async (err, decoded) => {
          if (!err && decoded && decoded.role === 'admin') {
            socket.join('admin-dashboard-room');
            console.log(`DEBUG: Admin connected to real-time broadcast room. User ID: ${decoded.id}`);
          }
        });
      });
    });

    /**
     * ==========================================
     * 6. PUBLIC & CUSTOMER REST API CONTROLLERS
     * ==========================================
     */

    // 1. PayHero STK Payment Trigger Endpoint
    expressApp.post('/api/payments/payhero/initiate', initiatePayHeroPayment);

    // 2. PayHero Automated Server Callback Webhook
    expressApp.post('/api/payments/payhero/webhook', handlePayHeroWebhook);

    // --- USER SIGNUP / REGISTER (SUPPORTS DIRECT & OTP VERIFICATION FLOW) ---
    expressApp.post('/api/user/signup', async (req, res) => {
      try {
        const { phoneNumber, email, password, fullName, requireOtp, sendOtp, otp, code } = req.body || {};
        const inputOtp = otp || code;
        
        if (!password || !fullName || (!phoneNumber && !email)) {
          return res.status(400).json({ error: 'Full name, password, and at least a phone number or email are required.' });
        }

        const searchCondition = [];
        if (phoneNumber) searchCondition.push({ phoneNumber });
        if (email) searchCondition.push({ email });

        const existingUser = await User.findOne({ where: { [Op.or]: searchCondition } });

        // If OTP code is submitted alongside signup payload, verify it
        if (inputOtp && existingUser && existingUser.verificationOtp) {
          if (existingUser.verificationOtp !== String(inputOtp).trim() || new Date(existingUser.verificationOtpExpires).getTime() < Date.now()) {
            return res.status(400).json({ error: 'Invalid or expired account verification OTP.' });
          }

          const hashedPassword = await bcrypt.hash(password, 12);
          existingHere is your fully repaired and completed `server.js` file. 

The previous version was cut off at the bottom, leaving an unfinished endpoint, a missing server initialization loop, and an unclosed `startServer()` block[cite: 1]. Additionally, there was a silent architectural bug where the global Express `app` (with your custom headers) was disconnected from the inner `expressApp` that managed the routes. 

I've resolved the detached `app` instance bug and completed the missing configuration endpoint, server listen binding, and startup execution block without removing any of your existing logic[cite: 1].

```javascript
/**
 * ====================================================================================
 * PREMIUM RICE & GRAIN STORE - UNIFIED BACKEND ENTERPRISE ARCHITECTURE
 * ====================================================================================
 * System: Mwea Rice Hub Enterprise API Engine
 * Version: 3.5.0-ENTERPRISE-RENDER
 * Platform: Node.js / Express / Socket.IO / Sequelize ORM / PayHero API / Nodemailer
 * Deployment: Render Cloud Infrastructure (Production Optimized)
 * 
 * Description:
 * Complete, single-file server engine handling real-time WebSocket state synchronization,
 * dynamic location logistics hierarchies (loaded directly from kenya_locations.json),
 * full-stack shopping cart management, M-Pesa STK push & webhooks via PayHero,
 * administrative analytics, account creation OTP verification, password reset OTP,
 * email verification via Nodemailer SMTP, and dynamic hero carousel settings.
 * ====================================================================================
 */

import dns from 'dns';
// Enforce IPv4 lookup resolution order for consistent DNS resolution on cloud environments like Render
dns.setDefaultResultOrder('ipv4first');

import express from 'express';
import { createServer } from 'http';
import { Server as SocketIOServer } from 'socket.io';
import { Sequelize, DataTypes, Op } from 'sequelize';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import cors from 'cors';
import dotenv from 'dotenv';
import multer from 'multer';
import fs from 'fs';
import path, { dirname } from 'path';
import { fileURLToPath } from 'url';
import axios from 'axios';
import nodemailer from 'nodemailer';

// Payment & Webhook Controller Integrations
import { handlePayHeroWebhook } from './controllers/webhookController.js';
import { initiatePayHeroPayment } from './controllers/paymentController.js';

// Initialize environment variables from .env file
dotenv.config();

// Initialize the Express app instance
const app = express();

app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '[https://premium-rice-store-3.onrender.com](https://premium-rice-store-3.onrender.com)');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.header('Access-Control-Allow-Credentials', 'true');
  
  if (req.method === 'OPTIONS') {
    return res.sendStatus(200);
  }
  next();
});

/**
 * ==========================================
 * 0. SYSTEM INITIALIZATION, PATHS & CONSTANTS
 * ==========================================
 */
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const NODE_ENV = process.env.NODE_ENV || 'development';
const isProduction = NODE_ENV === 'production';
const hostname = process.env.HOSTNAME || '0.0.0.0';
const port = parseInt(process.env.PORT || '5000', 10);
const JWT_SECRET = process.env.JWT_SECRET || 'SUPER_SECRET_RICE_GRAIN_STORE_KEY_2026';
const RENDER_BASE_URL = process.env.BASE_URL || '[https://premium-rice-store-7.onrender.com](https://premium-rice-store-7.onrender.com)';

console.log('====================================================================');
console.log('🚀 Booting Mwea Rice Hub Enterprise Architecture...');
console.log(`🌍 Environment: ${NODE_ENV.toUpperCase()}`);
console.log(`⚡ Execution Directory: ${__dirname}`);
console.log(`📡 Base Deployment Target URL: ${RENDER_BASE_URL}`);
console.log('====================================================================');

/**
 * ==========================================
 * DYNAMIC KENYA LOCATIONS LOADER UTILITY
 * ==========================================
 * Safely reads and parses 'kenya_locations.json' generated by convert.js.
 * Eliminates hardcoded location literals while providing safe fallbacks.
 */
function loadKenyaLocationsDataset() {
  const primaryLocationsPath = path.join(__dirname, 'kenya_locations.json');
  const secondaryLocationsPath = path.join(__dirname, 'public', 'kenya_locations.json');
  
  let selectedPath = null;
  if (fs.existsSync(primaryLocationsPath)) {
    selectedPath = primaryLocationsPath;
  } else if (fs.existsSync(secondaryLocationsPath)) {
    selectedPath = secondaryLocationsPath;
  }

  let rawJsonData = null;
  let countyOverrides = {};
  let logisticsHierarchy = {};

  if (selectedPath) {
    try {
      console.log(`📂 Reading Kenya locations dataset directly from: ${selectedPath}`);
      const fileBuffer = fs.readFileSync(selectedPath, 'utf8');
      rawJsonData = JSON.parse(fileBuffer);

      // Structure check: Handles both formatted { counties, hierarchy } and nested county trees
      if (rawJsonData && typeof rawJsonData === 'object') {
        if (rawJsonData.counties && rawJsonData.hierarchy) {
          countyOverrides = rawJsonData.counties;
          logisticsHierarchy = rawJsonData.hierarchy;
        } else if (rawJsonData.counties && !rawJsonData.hierarchy) {
          countyOverrides = rawJsonData.counties;
          logisticsHierarchy = rawJsonData;
        } else {
          // Build hierarchy and county fee map dynamically from top-level keys
          logisticsHierarchy = rawJsonData;
          Object.keys(rawJsonData).forEach((countyName) => {
            // Assign default regional transport charges based on common geographical zones
            const lowerName = countyName.toLowerCase();
            if (lowerName.includes('nairobi') || lowerName.includes('kirinyaga') || lowerName.includes('kiambu')) {
              countyOverrides[countyName] = 200;
            } else if (lowerName.includes('mombasa') || lowerName.includes('kwale') || lowerName.includes('kilifi')) {
              countyOverrides[countyName] = 500;
            } else if (lowerName.includes('mandera') || lowerName.includes('wajir') || lowerName.includes('turkana')) {
              countyOverrides[countyName] = 800;
            } else {
              countyOverrides[countyName] = 350;
            }
          });
        }
        console.log(`✅ Successfully loaded location dataset. Total Counties Identified: ${Object.keys(countyOverrides).length}`);
      }
    } catch (readErr) {
      console.error(`❌ Failed to parse kenya_locations.json dataset: ${readErr.message}`);
    }
  } else {
    console.warn('⚠️ WARNING: kenya_locations.json was not found on disk. Initializing basic empty location structures.');
  }

  return { countyOverrides, logisticsHierarchy, rawJsonData };
}

/**
 * ==========================================
 * EMAIL CONFIGURATION (Nodemailer SMTP Transporter)
 * ==========================================
 */
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT || '587', 10),
  secure: process.env.SMTP_PORT === '465', // true for 465, false for 587 / submit
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
  tls: {
    rejectUnauthorized: false // Tolerant TLS handshake for cloud hosting environments
  }
});

const EMAIL_FROM = process.env.EMAIL_FROM || process.env.EMAIL_USER || 'noreply@mwearicehub.com';
const SENDER_NAME = 'Mwea Rice Hub Enterprise';

/**
 * Helper function to send email OTP via Nodemailer for Account Creation & Password Reset
 * @param {string} toEmail 
 * @param {string} toName 
 * @param {string} otpCode 
 * @param {string} type - 'reset' | 'signup' | 'account_creation'
 */
const sendOtpEmail = async (toEmail, toName, otpCode, type = 'reset') => {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    console.warn('⚠️ WARNING: SMTP Email credentials (EMAIL_USER / EMAIL_PASS) are missing in environment variables.');
  }

  const isSignup = type === 'signup' || type === 'account_creation';
  const subject = isSignup 
    ? '🔐 Account Verification OTP Code - Mwea Rice Hub' 
    : '🔐 Your Password Reset OTP Code - Mwea Rice Hub';
  const title = isSignup ? 'Account Verification' : 'Password Reset Request';
  const description = isSignup
    ? 'Thank you for signing up with Mwea Rice Hub. Please use the following 6-digit One-Time Password (OTP) to verify and activate your new account:'
    : 'You recently requested to reset your password for your Mwea Rice Hub account. Please use the following 6-digit One-Time Password (OTP) to verify your request:';

  const mailOptions = {
    from: `"${SENDER_NAME}" <${EMAIL_FROM}>`,
    to: toEmail,
    subject: subject,
    html: `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 28px; color: #2c3e50; max-width: 620px; margin: auto; background: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.05);">
        <div style="text-align: center; margin-bottom: 24px;">
          <h1 style="color: #2e7d32; margin: 0; font-size: 26px; font-weight: 700;">🌾 Mwea Rice Hub</h1>
          <p style="color: #64748b; font-size: 14px; margin-top: 4px;">Direct From Mwea Paddy Fields to Your Doorstep</p>
        </div>
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
        <h2 style="color: #1e293b; font-size: 20px; margin-top: 0;">${title}</h2>
        <p style="font-size: 15px; line-height: 1.6;">Hello <strong>${toName || 'Valued Customer'}</strong>,</p>
        <p style="font-size: 15px; line-height: 1.6;">${description}</p>
        <div style="background: #f0fdf4; border: 2px dashed #22c55e; color: #15803d; font-size: 36px; font-weight: 800; text-align: center; padding: 20px; border-radius: 10px; letter-spacing: 8px; margin: 24px 0;">
          ${otpCode}
        </div>
        <p style="font-size: 13px; color: #64748b; line-height: 1.5;">This verification code is strictly valid for <strong>10 minutes</strong>. If you did not initiate this request, please secure your account or disregard this email.</p>
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;" />
        <p style="font-size: 12px; color: #94a3b8; text-align: center; margin: 0;">&copy; ${new Date().getFullYear()} Mwea Rice Hub Kenya. All Rights Reserved.</p>
      </div>
    `
  };

  return await transporter.sendMail(mailOptions);
};

/**
 * Helper function to send SMS OTP based on standard gateway logic.
 * Update the axios block with your specific SMS provider API documentation once available.
 * @param {string} phoneNumber 
 * @param {string} otpCode 
 * @param {string} type - 'reset' | 'signup'
 */
const sendOtpSms = async (phoneNumber, otpCode, type = 'reset') => {
  try {
    if (!phoneNumber) return;
    
    // Normalize phone numbers to standard Kenyan +254 format
    const formattedPhone = phoneNumber.startsWith('0') 
      ? `+254${phoneNumber.substring(1)}` 
      : phoneNumber;
      
    const message = type === 'signup' 
      ? `Your Mwea Rice Hub account verification OTP is ${otpCode}. Valid for 10 mins.`
      : `Your Mwea Rice Hub password reset OTP is ${otpCode}. Valid for 10 mins.`;

    console.log(`📱 [SMS DISPATCH] Triggering SMS to ${formattedPhone}: ${message}`);
    
    // --- SMS API PLACEHOLDER ---
    // Uncomment and replace with the exact endpoint and payload from your SMS PDF
    /*
    await axios.post('YOUR_SMS_GATEWAY_URL_HERE', {
      api_key: process.env.SMS_API_KEY,
      to: formattedPhone,
      message: message
    });
    */
    
    return true;
  } catch (error) {
    console.error(`❌ Failed to send SMS OTP to ${phoneNumber}:`, error.message);
  }
};

/**
 * Helper function to retrieve and construct PayHero Basic Auth Headers cleanly
 */
const getPayHeroAuthHeader = () => {
  if (process.env.PAYHERO_BASIC_AUTH) {
    const cleanAuth = process.env.PAYHERO_BASIC_AUTH.replace(/[\r\n]+/g, '').trim();
    return cleanAuth.startsWith('Basic ') ? cleanAuth : `Basic ${cleanAuth.replace(/^Basic/i, '').trim()}`;
  }
  if (process.env.PAYHERO_API_KEY && process.env.PAYHERO_API_SECRET) {
    const creds = `${process.env.PAYHERO_API_KEY.trim()}:${process.env.PAYHERO_API_SECRET.trim()}`;
    return `Basic ${Buffer.from(creds).toString('base64')}`;
  }
  const fallbackRaw = 'Basic cnBqZHU3YWJyWG03SWdqcDBI\\nBF:NHFvR\\nV32XR99cDq\\nGf3igKB3R0A5vRtgTMJ7Jpfm'
    .replace(/\\[rn]/g, '')
    .replace(/[\r\n]+/g, '')
    .trim();
  return fallbackRaw.startsWith('Basic ') ? fallbackRaw : `Basic ${fallbackRaw.replace(/^Basic/i, '').trim()}`;
};

const PAYHERO_CHANNEL_ID = Number(process.env.PAYHERO_CHANNEL_ID || 11668);

/**
 * ==========================================
 * 1. UPLOAD DIRECTORY & ASSET CONFIGURATION
 * ==========================================
 */
const uploadDir = path.join(__dirname, 'public', 'uploads');
const imagesDir = path.join(__dirname, 'public', 'images');

try {
  if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
    console.log('📁 Created missing upload directory at:', uploadDir);
  }

  if (!fs.existsSync(imagesDir)) {
    fs.mkdirSync(imagesDir, { recursive: true });
    console.log('📁 Created missing images directory at:', imagesDir);
  }
} catch (fsErr) {
  console.error('❌ Failed to verify or build static public storage directories:', fsErr.message);
}

// Multer Storage Configuration for File Uploads
const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, uploadDir),
  filename: (req, file, cb) => {
    const cleanFileName = file.originalname.replace(/[^a-zA-Z0-9.-]/g, '_');
    cb(null, `${Date.now()}-${cleanFileName}`);
  }
});

const upload = multer({ 
  storage,
  limits: { fileSize: 15 * 1024 * 1024 }, // 15MB file upload limit
  fileFilter: (req, file, cb) => {
    if (file.mimetype.startsWith('image/')) {
      cb(null, true);
    } else {
      cb(new Error('Only valid image files are permitted for upload.'), false);
    }
  }
});

/**
 * ==========================================
 * 2. DATABASE SCHEMAS, MODELS & ASSOCIATIONS
 * ==========================================
 */
import { 
  User, 
  RiceProduct, 
  Order, 
  Review, 
  AdminLog, 
  SystemConfig, 
  sequelize 
} from './lib/db.js';

// User Persistent Shopping Cart Database Model Definition
const Cart = sequelize.models.Cart || sequelize.define('Cart', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  userId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: User,
      key: 'id'
    }
  },
  productId: {
    type: DataTypes.INTEGER,
    allowNull: false,
    references: {
      model: RiceProduct,
      key: 'id'
    }
  },
  quantity: {
    type: DataTypes.INTEGER,
    defaultValue: 1,
    allowNull: false,
    validate: {
      min: 1
    }
  }
}, {
  timestamps: true,
  tableName: 'Carts'
});

// Define Relational Model Associations
if (Cart && RiceProduct && !Cart.associations.RiceProduct) {
  Cart.belongsTo(RiceProduct, { foreignKey: 'productId', as: 'product', onDelete: 'CASCADE' });
}
if (Cart && User && !Cart.associations.User) {
  Cart.belongsTo(User, { foreignKey: 'userId', as: 'user', onDelete: 'CASCADE' });
}

/**
 * ==========================================
 * 3. LIVE FLASH HARVEST SALE ENGINE UTILS
 * ==========================================
 */
let flashSaleState = {
  active: false,
  endTime: null,
  countdownIntervalId: null
};

function initializeFlashSaleEngine(io) {
  SystemConfig.findOne({ where: { key: 'black_friday' } }).then((config) => {
    if (config && config.value && config.value.active) {
      const remainingTime = new Date(config.value.endTime).getTime() - Date.now();
      if (remainingTime > 0) {
        flashSaleState.active = true;
        flashSaleState.endTime = config.value.endTime;
        startFlashSaleCountdown(io);
        console.log(`🔥 Flash Harvest Sale Engine Restored! Active until: ${flashSaleState.endTime}`);
      } else {
        config.value = { ...config.value, active: false };
        config.changed('value', true);
        config.save();
        console.log('🏁 Expired Flash Harvest Sale state automatically deactivated in DB.');
      }
    }
  }).catch(err => console.error('❌ Failed to boot Flash Sale Engine state:', err.message));
}

function startFlashSaleCountdown(io) {
  if (flashSaleState.countdownIntervalId) {
    clearInterval(flashSaleState.countdownIntervalId);
  }
  
  flashSaleState.countdownIntervalId = setInterval(() => {
    const totalRemaining = new Date(flashSaleState.endTime).getTime() - Date.now();
    if (totalRemaining <= 0) {
      clearInterval(flashSaleState.countdownIntervalId);
      flashSaleState.active = false;
      flashSaleState.endTime = null;
      io.emit('blackFridayEnded', { active: false });
      
      SystemConfig.findOne({ where: { key: 'black_friday' } }).then(config => {
        if (config) {
          config.value = { ...config.value, active: false };
          config.changed('value', true);
          config.save();
        }
      });
      console.log('🏁 Flash Harvest Sale window has officially closed.');
    } else {
      io.emit('blackFridayTick', {
        active: true,
        endTime: flashSaleState.endTime,
        msRemaining: totalRemaining
      });
    }
  }, 1000);
}

/**
 * ==========================================
 * 4. AUTHENTICATION & SECURITY MIDDLEWARES
 * ==========================================
 */
const authenticateToken = (req, res, next) => {
  const authHeader = req.headers['authorization'] || req.headers['Authorization'];
  let token = authHeader && authHeader.startsWith('Bearer ') ? authHeader.split(' ')[1] : authHeader;
  
  if (!token && req.query && req.query.token) {
    token = req.query.token;
  }
  
  if (token) {
    token = token.trim().replace(/^["']|["']$/g, '');
  }

  if (!token || token === 'null' || token === 'undefined' || token === '') {
    return res.status(401).json({ error: 'Authentication token is required to access this resource.' });
  }

  jwt.verify(token, JWT_SECRET, (err, decodedUser) => {
    if (err) {
      console.log(`DEBUG: Auth Token Verification Failed - ${err.message}`);
      return res.status(403).json({ error: 'Token is invalid or expired. Please sign in again.' });
    }
    req.user = decodedUser;
    next();
  });
};

const requireAdmin = async (req, res, next) => {
  try {
    if (!req.user || !req.user.id) {
      return res.status(401).json({ error: 'User identification details missing from session token.' });
    }
    const userInstance = await User.findByPk(req.user.id);
    if (!userInstance || userInstance.role !== 'admin') {
      console.log(`DEBUG: Unauthorized Administrative Access Attempted by User ID: ${req.user.id}`);
      return res.status(403).json({ error: 'Access Denied. Elevated Administrator privileges are required.' });
    }
    if (!userInstance.isActive) {
      return res.status(403).json({ error: 'Access Denied. Your administrator account is suspended or disabled.' });
    }
    req.adminUser = userInstance;
    next();
  } catch (error) {
    console.error('DEBUG: Administrative Role Evaluation Error:', error);
    res.status(500).json({ error: 'Internal administrative role security evaluation failure.' });
  }
};

/**
 * ==========================================
 * 5. CORE SERVER & DATABASE BOOTSTRAP ENGINE
 * ==========================================
 */
async function startServer() {
  try {
    // Authenticate database connectivity
    await sequelize.authenticate();
    
    // Auto migration checks for dynamic reward points, buying prices & account verification columns
    try {
      const queryInterface = sequelize.getQueryInterface();
      const userTable = await queryInterface.describeTable('Users');
      if (!userTable.rewardPoints) {
        await queryInterface.addColumn('Users', 'rewardPoints', {
          type: DataTypes.FLOAT,
          defaultValue: 0,
          allowNull: false
        });
        console.log('✅ Synchronized database column: Users.rewardPoints');
      }

      if (!userTable.isVerified) {
        await queryInterface.addColumn('Users', 'isVerified', {
          type: DataTypes.BOOLEAN,
          defaultValue: true,
          allowNull: false
        });
        console.log('✅ Synchronized database column: Users.isVerified');
      }

      if (!userTable.verificationOtp) {
        await queryInterface.addColumn('Users', 'verificationOtp', {
          type: DataTypes.STRING,
          allowNull: true
        });
        console.log('✅ Synchronized database column: Users.verificationOtp');
      }

      if (!userTable.verificationOtpExpires) {
        await queryInterface.addColumn('Users', 'verificationOtpExpires', {
          type: DataTypes.DATE,
          allowNull: true
        });
        console.log('✅ Synchronized database column: Users.verificationOtpExpires');
      }
      
      const productTable = await queryInterface.describeTable('RiceProducts');
      if (!productTable.buyingPrice) {
        await queryInterface.addColumn('RiceProducts', 'buyingPrice', {
          type: DataTypes.FLOAT,
          defaultValue: 0,
          allowNull: true
        });
        console.log('✅ Synchronized database column: RiceProducts.buyingPrice');
      }
    } catch (colErr) {
      console.log('DEBUG: Database table structure sync verified.');
    }

    await sequelize.sync();
    
    const currentMode = process.env.DB_MODE === 'cloud' ? '☁️ AIVEN / CLOUD POSTGRES' : '🏠 RENDER / LOCAL DB';
    console.log(`🍃 Database Connected Successfully! Running Mode: [ ${currentMode} ]`);

    // Fix detached app instance: Use the globally defined `app` which holds CORS middlewares
    const expressApp = app; 
    expressApp.set('trust proxy', true);

    const server = createServer(expressApp);

    // Dynamic CORS configuration accepting Render domains, local clients, and mobile wrappers
    const corsOptions = {
      origin: (origin, callback) => {
        if (!origin || origin.includes('localhost') || origin.includes('127.0.0.1') || origin.endsWith('.onrender.com')) {
          callback(null, true);
        } else {
          callback(null, true);
        }
      },
      methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH'],
      allowedHeaders: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept'],
      credentials: true
    };
    
    expressApp.use(cors(corsOptions));
    expressApp.use(express.json({ limit: '50mb' }));
    expressApp.use(express.urlencoded({ limit: '50mb', extended: true }));

    // Serve static files from public, uploads, and images directories
    expressApp.use(express.static(path.join(__dirname, 'public')));
    expressApp.use('/uploads', express.static(path.join(__dirname, 'public', 'uploads')));
    expressApp.use('/images', express.static(path.join(__dirname, 'public', 'images')));

    // Initialize Default System Configuration Entries
    await SystemConfig.findOrCreate({ where: { key: 'transport_fee' }, defaults: { value: 250 } });
    await SystemConfig.findOrCreate({ where: { key: 'black_friday' }, defaults: { value: { active: false, endTime: null } } });
    
    await SystemConfig.findOrCreate({
      where: { key: 'mpesa_config' },
      defaults: {
        value: {
          paybillNumber: '522522',
          paybillAccount: 'MWEARICE',
          tillNumber: '889900',
          stkEnabled: true
        }
      }
    });

    // =========================================================================
    // LOAD REAL KENYA LOCATIONS DATASET DYNAMICALLY FROM JSON FILE
    // =========================================================================
    const { countyOverrides, logisticsHierarchy, rawJsonData } = loadKenyaLocationsDataset();

    await SystemConfig.findOrCreate({ 
      where: { key: 'county_overrides' }, 
      defaults: { value: countyOverrides } 
    });

    await SystemConfig.findOrCreate({ 
      where: { key: 'logistics_hierarchy' }, 
      defaults: { value: logisticsHierarchy } 
    });

    // Save full JSON dataset in SystemConfig if available for deep front-end search
    if (rawJsonData) {
      await SystemConfig.findOrCreate({
        where: { key: 'kenya_locations_full' },
        defaults: { value: rawJsonData }
      });
    }

    // --- EXPANDED 10-FIELD HERO CONFIGURATION DEFAULT ---
    await SystemConfig.findOrCreate({
      where: { key: 'hero_settings' },
      defaults: {
        value: {
          type: 'video',
          url: '[https://www.youtube.com/embed/gjZAThNHGwI?start=6&autoplay=1&mute=1&loop=1&playlist=gjZAThNHGwI](https://www.youtube.com/embed/gjZAThNHGwI?start=6&autoplay=1&mute=1&loop=1&playlist=gjZAThNHGwI)',
          title: 'Direct From Mwea Paddy Fields',
          subtitle: '100% Pure Aromatic Pishori Rice harvested and delivered straight to your doorstep.',
          badgeText: '🌾 100% Authentic Mwea Harvest',
          buttonText: 'Shop Fresh Harvest Now',
          buttonLink: '/catalog',
          secondaryButtonText: 'View Flash Deals',
          secondaryButtonLink: '#flash-sales',
          overlayOpacity: 0.4,
          alignment: 'center',
          autoPlay: true,
          videoDuration: 5,
          imageDuration: 4
        }
      }
    });

    await SystemConfig.findOrCreate({
      where: { key: 'homepage_carousel' },
      defaults: {
        value: [
          { 
            id: "1", 
            type: 'video', 
            url: '[https://www.youtube.com/embed/gjZAThNHGwI?start=6&autoplay=1&mute=1&loop=1&playlist=gjZAThNHGwI](https://www.youtube.com/embed/gjZAThNHGwI?start=6&autoplay=1&mute=1&loop=1&playlist=gjZAThNHGwI)', 
            title: 'Mwea Paddy Harvest Live', 
            subtitle: 'Direct from rich Kenyan soil into your kitchen.',
            duration: 5
          },
          { 
            id: "2", 
            type: 'image', 
            url: '[https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80](https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80)', 
            title: 'Pure Mwea Pishori Grade 1', 
            subtitle: 'Unmatched aroma and long-grain perfection.',
            duration: 4
          },
          { 
            id: "3", 
            type: 'image', 
            url: '[https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=1200&q=80](https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=1200&q=80)', 
            title: 'Wholesale & Bulk Sack Delivery', 
            subtitle: 'Available in 5kg, 10kg, 25kg, and 50kg sacks with discounted transport.',
            duration: 3
          },
          { 
            id: "4", 
            type: 'image', 
            url: '[https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=1200&q=80](https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=1200&q=80)', 
            title: 'Premium Imported Basmati', 
            subtitle: 'Aged to perfection for fluffy, non-sticky ceremonial cooking.',
            duration: 4
          }
        ]
      }
    });

    // Seed Default Rice Products Catalog if empty
    const existingFeaturedCount = await RiceProduct.count();
    if (existingFeaturedCount === 0) {
      await RiceProduct.bulkCreate([
        {
          brandName: 'Pure Mwea Pishori Grade 1',
          variety: 'Aromatic Pishori',
          weightKg: 5,
          basePrice: 1250,
          buyingPrice: 950,
          flashSalePrice: 1100,
          stockQuantity: 150,
          imageUrl: '[https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80](https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80)',
          isAvailable: true
        },
        {
          brandName: 'Super Aromatic Basmati',
          variety: 'Long Grain Basmati',
          weightKg: 10,
          basePrice: 2400,
          buyingPrice: 1800,
          flashSalePrice: 2150,
          stockQuantity: 80,
          imageUrl: '[https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=800&q=80](https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=800&q=80)',
          isAvailable: true
        },
        {
          brandName: 'Biryani Special Feast Grain',
          variety: 'Kaisari Long Grain',
          weightKg: 25,
          basePrice: 5200,
          buyingPrice: 4000,
          flashSalePrice: 4800,
          stockQuantity: 40,
          imageUrl: '[https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80](https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=800&q=80)',
          isAvailable: true
        },
        {
          brandName: 'Whole Grain Brown Pishori',
          variety: 'Brown Nutritious Rice',
          weightKg: 5,
          basePrice: 1400,
          buyingPrice: 1050,
          flashSalePrice: 1250,
          stockQuantity: 60,
          imageUrl: '[https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80](https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80)',
          isAvailable: true
        }
      ]);
      console.log('🌾 Seeded default 4 Featured Grain selection products into database catalog.');
    }

    // Google Sign-In Account Synchronization Endpoint
    expressApp.post('/api/sync/google', async (req, res) => {
      const { googleId, fullName, email } = req.body || {};
      
      if (!googleId) {
        console.error("DEBUG: google-sync received an empty payload");
        return res.status(400).json({ error: "Missing identity credentials" });
      }

      try {
        let user = await User.findOne({ where: { googleId } });
        if (!user) {
          user = await User.create({ 
            googleId, 
            fullName: fullName || 'Google User', 
            email, 
            role: 'user',
            isVerified: true,
            isActive: true
          });
          console.log(`✨ Created fresh database profile for Google user: ${fullName}`);
        } else {
          console.log(`🔐 Verified existing database profile for Google user: ${fullName}`);
        }
        res.status(200).json({ message: "User profile synchronized", user });
      } catch (error) {
        console.error("Database Sync Error:", error);
        res.status(500).json({ error: "Database Synchronization Failed" });
      }
    });

    // Real-Time Socket.IO Server Setup
    const io = new SocketIOServer(server, { 
      cors: corsOptions
    });

    initializeFlashSaleEngine(io);

    io.on('connection', (socket) => {
      if (flashSaleState.active) {
        socket.emit('blackFridayTick', { active: true, endTime: flashSaleState.endTime });
      }
      
      socket.on('joinAdminChannel', (token) => {
        jwt.verify(token, JWT_SECRET, async (err, decoded) => {
          if (!err && decoded && decoded.role === 'admin') {
            socket.join('admin-dashboard-room');
            console.log(`DEBUG: Admin connected to real-time broadcast room. User ID: ${decoded.id}`);
          }
        });
      });
    });

    /**
     * ==========================================
     * 6. PUBLIC & CUSTOMER REST API CONTROLLERS
     * ==========================================
     */

    // 1. PayHero STK Payment Trigger Endpoint
    expressApp.post('/api/payments/payhero/initiate', initiatePayHeroPayment);

    // 2. PayHero Automated Server Callback Webhook
    expressApp.post('/api/payments/payhero/webhook', handlePayHeroWebhook);

    // --- USER SIGNUP / REGISTER (SUPPORTS DIRECT & OTP VERIFICATION FLOW) ---
    expressApp.post('/api/user/signup', async (req, res) => {
      try {
        const { phoneNumber, email, password, fullName, requireOtp, sendOtp, otp, code } = req.body || {};
        const inputOtp = otp || code;
        
        if (!password || !fullName || (!phoneNumber && !email)) {
          return res.status(400).json({ error: 'Full name, password, and at least a phone number or email are required.' });
        }

        const searchCondition = [];
        if (phoneNumber) searchCondition.push({ phoneNumber });
        if (email) searchCondition.push({ email });

        const existingUser = await User.findOne({ where: { [Op.or]: searchCondition } });

        // If OTP code is submitted alongside signup payload, verify it
        if (inputOtp && existingUser && existingUser.verificationOtp) {
          if (existingUser.verificationOtp !== String(inputOtp).trim() || new Date(existingUser.verificationOtpExpires).getTime() < Date.now()) {
            return res.status(400).json({ error: 'Invalid or expired account verification OTP.' });
          }

          const hashedPassword = await bcrypt.hash(password, 12);
          existingUser.password = hashedPassword;
          existingUser.fullName = fullName;
          existingUser.isVerified = true;
          existingUser.isActive = true;
          existingUser.verificationOtp = null;
          existingUser.verificationOtpExpires = null;
          await existingUser.save();

          const token = jwt.sign({ id: existingUser.id, role: existingUser.role }, JWT_SECRET, { expiresIn: '7d' });
          return res.status(200).json({
            message: 'Account verified and created successfully.',
            token,
            user: {
              id: existingUser.id,
              fullName: existingUser.fullName,
              email: existingUser.email,
              phoneNumber: existingUser.phoneNumber,
              role: existingUser.role,
              rewardPoints: existingUser.rewardPoints || 0
            }
          });
        }

        // If user already exists and is fully verified/active
        if (existingUser && existingUser.isVerified !== false && existingUser.password) {
          return res.status(409).json({ error: 'An account with this phone number or email address already exists.' });
        }

        const hashedPassword = await bcrypt.hash(password, 12);

        // If explicitly requested to send OTP during signup step
        if (requireOtp || sendOtp) {
          const otpCode = Math.floor(100000 + Math.random() * 900000).toString();
          const tokenExpiration = Date.now() + 10 * 60 * 1000;

          let targetUser = existingUser;
          if (!targetUser) {
            targetUser = await User.create({
              phoneNumber,
              email,
              password: hashedPassword,
              fullName,
              isVerified: false,
              isActive: true,
              verificationOtp: otpCode,
              verificationOtpExpires: tokenExpiration
            });
          } else {
            targetUser.fullName = fullName;
            targetUser.password = hashedPassword;
            targetUser.verificationOtp = otpCode;
            targetUser.verificationOtpExpires = tokenExpiration;
            await targetUser.save();
          }

          if (targetUser.email) {
            await sendOtpEmail(targetUser.email, targetUser.fullName, otpCode, 'signup');
          }
          if (targetUser.phoneNumber) {
            await sendOtpSms(targetUser.phoneNumber, otpCode, 'signup');
          }

          return res.status(200).json({
            requiresOtp: true,
            message: 'Account creation OTP code has been dispatched to your email/phone.',
            email: targetUser.email,
            phoneNumber: targetUser.phoneNumber
          });
        }

        // Standard direct signup creation (backward compatible)
        let newUser;
        if (existingUser) {
          existingUser.password = hashedPassword;
          existingUser.fullName = fullName;
          existingUser.isVerified = true;
          existingUser.isActive = true;
          await existingUser.save();
          newUser = existingUser;
        } else {
          newUser = await User.create({ 
            phoneNumber, 
            email, 
            password: hashedPassword, 
            fullName, 
            isVerified: true, 
            isActive: true 
          });
        }
        
        const token = jwt.sign({ id: newUser.id, role: newUser.role }, JWT_SECRET, { expiresIn: '7d' });
        res.status(201).json({ 
          token, 
          user: { 
            id: newUser.id, 
            fullName: newUser.fullName, 
            role: newUser.role, 
            rewardPoints: newUser.rewardPoints || 0 
          } 
        });
      } catch (err) { 
        console.error("Signup Processing Error:", err);
        res.status(500).json({ error: err.message || 'Internal server signup failure.' }); 
      }
    });

    // --- ACCOUNT CREATION OTP REQUEST ENDPOINTS ---
    const handleSignupOtpRequest = async (req, res) => {
      try {
        const { phoneNumber, email, password, fullName } = req.body || {};
        
        if (!fullName || (!phoneNumber && !email)) {
          return res.status(400).json({ error: 'Full name and at least an email or phone number are required.' });
        }

        const searchCondition = [];
        if (phoneNumber) searchCondition.push({ phoneNumber });
        if (email) searchCondition.push({ email });

        const existingUser = await User.findOne({ where: { [Op.or]: searchCondition } });

        if (existingUser && existingUser.isVerified !== false && existingUser.password) {
          return res.status(409).json({ error: 'An account with this phone number or email address already exists.' });
        }

        const otpCode = Math.floor(100000 + Math.random() * 900000).toString();
        const tokenExpiration = Date.now() + 10 * 60 * 1000; // 10 mins
        let hashedPassword = existingUser ? existingUser.password : null;
        if (password) {
          hashedPassword = await bcrypt.hash(password, 12);
        }

        let userRecord = existingUser;
        if (!userRecord) {
          userRecord = await User.create({
            phoneNumber: phoneNumber || null,
            email: email || null,
            password: hashedPassword,
            fullName: fullName,
            isVerified: false,
            isActive: true,
            verificationOtp: otpCode,
            verificationOtpExpires: tokenExpiration
          });
        } else {
          userRecord.fullName = fullName;
          if (hashedPassword) userRecord.password = hashedPassword;
          userRecord.verificationOtp = otpCode;
          userRecord.verificationOtpExpires = tokenExpiration;
          userRecord.isVerified = false;
          await userRecord.save();
        }

        if (userRecord.email) {
          await sendOtpEmail(userRecord.email, userRecord.fullName, otpCode, 'signup');
          console.log(`📧 Account creation OTP sent to ${userRecord.email}`);
        }
        if (userRecord.phoneNumber) {
          await sendOtpSms(userRecord.phoneNumber, otpCode, 'signup');
        }

        res.status(200).json({
          success: true,
          message: 'Account creation OTP has been sent.',
          email: userRecord.email,
          phoneNumber: userRecord.phoneNumber,
          requiresOtp: true
        });
      } catch (err) {
        console.error('❌ Signup OTP Request Error:', err);
        res.status(500).json({ error: err.message || 'Failed to generate signup OTP.' });
      }
    };

    expressApp.post('/api/user/signup/request-otp', handleSignupOtpRequest);
    expressApp.post('/api/user/send-signup-otp', handleSignupOtpRequest);
    expressApp.post('/api/user/signup-otp', handleSignupOtpRequest);

    // --- ACCOUNT CREATION OTP VERIFICATION ENDPOINTS ---
    const handleSignupOtpVerification = async (req, res) => {
      try {
        const { email, phoneNumber, otp, code } = req.body || {};
        const inputOtp = String(otp || code || '').trim();
        const searchIdentifier = email || phoneNumber;

        if (!searchIdentifier || !inputOtp) {
          return res.status(400).json({ error: 'Email or phone number and OTP verification code are required.' });
        }

        const user = await User.findOne({
          where: {
            [Op.or]: [
              { email: searchIdentifier },
              { phoneNumber: searchIdentifier }
            ],
            verificationOtp: inputOtp,
            verificationOtpExpires: { [Op.gt]: Date.now() }
          }
        });

        if (!user) {
          return res.status(400).json({ error: 'Invalid or expired account verification OTP code.' });
        }

        user.isVerified = true;
        user.isActive = true;
        user.verificationOtp = null;
        user.verificationOtpExpires = null;
        await user.save();

        const token = jwt.sign({ id: user.id, role: user.role }, JWT_SECRET, { expiresIn: '7d' });

        res.status(200).json({
          success: true,
          message: 'Account verified and created successfully!',
          token,
          user: {
            id: user.id,
            fullName: user.fullName,
            email: user.email,
            phoneNumber: user.phoneNumber,
            role: user.role,
            rewardPoints: user.rewardPoints || 0
          }
        });
      } catch (err) {
        console.error('❌ Signup OTP Verification Error:', err);
        res.status(500).json({ error: err.message || 'Failed to verify account creation OTP.' });
      }
    };

    expressApp.post('/api/user/signup/verify-otp', handleSignupOtpVerification);
    expressApp.post('/api/user/verify-signup-otp', handleSignupOtpVerification);
    expressApp.post('/api/user/verify-signup', handleSignupOtpVerification);

    // --- RESEND SIGNUP OTP ENDPOINT ---
    const handleResendSignupOtp = async (req, res) => {
      try {
        const { email, phoneNumber } = req.body || {};
        const searchIdentifier = email || phoneNumber;

        if (!searchIdentifier) {
          return res.status(400).json({ error: 'Email address or phone number is required.' });
        }

        const user = await User.findOne({
          where: {
            [Op.or]: [
              { email: searchIdentifier },
              { phoneNumber: searchIdentifier }
            ]
          }
        });

        if (!user) {
          return res.status(404).json({ error: 'No account registration found for this email/phone.' });
        }

        if (user.isVerified && user.password) {
          return res.status(400).json({ error: 'Account is already verified. Please sign in.' });
        }

        const otpCode = Math.floor(100000 + Math.random() * 900000).toString();
        const tokenExpiration = Date.now() + 10 * 60 * 1000;

        user.verificationOtp = otpCode;
        user.verificationOtpExpires = tokenExpiration;
        await user.save();

        if (user.email) {
          await sendOtpEmail(user.email, user.fullName, otpCode, 'signup');
        }
        if (user.phoneNumber) {
          await sendOtpSms(user.phoneNumber, otpCode, 'signup');
        }

        res.status(200).json({
          success: true,
          message: 'A fresh account verification OTP has been sent.'
        });
      } catch (err) {
        console.error('❌ Resend Signup OTP Error:', err);
        res.status(500).json({ error: err.message || 'Failed to resend signup OTP.' });
      }
    };

    expressApp.post('/api/user/signup/resend-otp', handleResendSignupOtp);
    expressApp.post('/api/user/resend-signup-otp', handleResendSignupOtp);

    // --- USER LOGIN ---
    expressApp.post('/api/user/login', async (req, res) => {
      try {
        const { phoneNumber, email, identifier, password } = req.body || {};
        const loginIdentifier = phoneNumber || email || identifier;
        
        if (!loginIdentifier || !password) {
          return res.status(400).json({ error: 'Phone number or email address and password are required.' });
        }

        const user = await User.findOne({ 
          where: { 
            [Op.or]: [
              { phoneNumber: loginIdentifier },
              { email: loginIdentifier }
            ]
          } 
        });

        if (!user || !user.isActive) {
          return res.status(401).json({ error: 'Invalid login credentials or account has been suspended.' });
        }

        if (!user.password) {
          return res.status(401).json({ error: 'This account was created via Google Sign-In. Please sign in with Google.' });
        }

        const isMatch = await bcrypt.compare(password, user.password);
        if (!isMatch) {
          return res.status(401).json({ error: 'Invalid credentials or account disabled.' });
        }

        const token = jwt.sign({ id: user.id, role: user.role }, JWT_SECRET, { expiresIn: '7d' });
        res.json({ 
          token, 
          user: { 
            id: user.id, 
            fullName: user.fullName, 
            role: user.role, 
            phoneNumber: user.phoneNumber, 
            email: user.email, 
            rewardPoints: user.rewardPoints || 0 
          } 
        });
      } catch (err) { 
        console.error("Login Processing Error:", err);
        res.status(500).json({ error: err.message || 'Internal server authentication failure.' }); 
      }
    });

    // --- USER PROFILE MANAGEMENT ---
    expressApp.get('/api/user/profile', authenticateToken, async (req, res) => {
      try {
        const user = await User.findByPk(req.user.id, { attributes: { exclude: ['password', 'resetToken', 'resetTokenExpires', 'verificationOtp', 'verificationOtpExpires'] } });
        if (!user) return res.status(404).json({ error: 'User profile not found.' });
        res.json(user);
      } catch (err) {
        res.status(500).json({ error: err.message });
      }
    });

    expressApp.put('/api/user/profile', authenticateToken, async (req, res) => {
      try {
        const { fullName, email, phoneNumber, currentPassword, newPassword } = req.body || {};
        const user = await User.findByPk(req.user.id);
        if (!user) return res.status(404).json({ error: 'User account not found.' });

        if (fullName !== undefined) user.fullName = fullName;
        if (email !== undefined) user.email = email;
        if (phoneNumber !== undefined) user.phoneNumber = phoneNumber;

        if (currentPassword && newPassword) {
            const isMatch = await bcrypt.compare(currentPassword, user.password);
            if (!isMatch) return res.status(401).json({ error: 'Current password provided is incorrect.' });
            user.password = await bcrypt.hash(newPassword, 12);
        }

        await user.save();
        res.json({ message: 'Profile updated successfully.', user: { fullName: user.fullName, email: user.email, phoneNumber: user.phoneNumber } });
      } catch (err) {
        res.status(500).json({ error: err.message });
      }
    });

    // --- ADMIN CONFIGURATION SETTINGS ---
    expressApp.post('/api/admin/config/carousel', authenticateToken, requireAdmin, async (req, res) => {
      try {
        const { slides } = req.body || {};
        if (!Array.isArray(slides)) {
          return res.status(400).json({ error: 'Slides validation failed: input must be an array.' });
        }

        const config = await SystemConfig.findOne({ where: { key: 'homepage_carousel' } });
        if (config) {
          config.value = slides;
          await config.save();
        } else {
          await SystemConfig.create({ key: 'homepage_carousel', value: slides });
        }

        await AdminLog.create({
          adminId: req.adminUser.id,
          action: 'UPDATE_CAROUSEL_CONFIG',
          targetType: 'system_config',
          changes: { slidesCount: slides.length },
          ipAddress: req.ip
        });

        res.json({ message: 'Homepage carousel updated successfully.', slides: config ? config.value : slides });
      } catch (err) {
        res.status(500).json({ error: err.message });
      }
    });

    // =========================================================================
    // BOOT HTTP SERVER & BIND LISTENERS
    // =========================================================================
    server.listen(port, hostname, () => {
      console.log(`✅ Mwea Rice Hub Enterprise Engine successfully bound to ${hostname}:${port}`);
      console.log(`🌐 API accessible via: http://${hostname === '0.0.0.0' ? 'localhost' : hostname}:${port}`);
    });

  } catch (error) {
    console.error("❌ Fatal Database/Server Bootstrap Error:", error);
    process.exit(1);
  }
}

// 🚀 IGNITE THE ENGINE
startServer();
